schema_version = "1.0.0"

id = "Launch_Production_Kit"
name = "Launch Production Kit"
version = "0.1.8"
tagline = "Production shortcuts and toolsets"
maintainer = "John Einselen <jeinselen@gmail.com>"
website = "https://github.com/jeinselen/Blender-ProductionKit"
type = "add-on"

# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Material", "Pipeline", "Render", "Scene"]

blender_version_min = "4.5.0"
#blender_version_max = "5.9.9"

# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = ["SPDX:GPL-3.0-or-later"]

# Credit for third-party code bundled/adapted in the extension.
# The easing functions in driver_functions.py are adapted from Robert Penner's
# easing equations (https://easings.net/).
copyright = ["2001 Robert Penner"]

## Optional: add-ons can list which resources they will require:
## * files (for access of any filesystem operations)
## * network (for internet access)
## * clipboard (to read and/or write the system clipboard)
## * camera (to capture photos and videos)
## * microphone (to capture audio)
##
## If using network, remember to also check `bpy.app.online_access`
## https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
##
[permissions]
files = "Saving colour palettes and versioned project files"
clipboard = "Copy and paste colour swatches and driver expressions"
